### Gradient Descent - Intuition

- Suppose you are lost in the mountains in a dense fog; you can only feel the slope of the ground below your feet. A good strategy to get to the bottom of the valley quickly is to go downhill in the direction of the steepest slope. This is exactly what `GradientDescent` does.
- It measures the local gradient of the error function with regards to the parameter vector `theta`, and it goes in the direction of descending gradient.


- **Note**: Use `StandardScaler` to scale all the features before applying `GradientDescent`. Otherwise, it would take much longer to converge to an optima.
- It is a search in the model’s parameter space: the more parameters a model has, the more dimensions this space has, and the harder the search is.
- Compared to Normal Equation method, `GradientDescent` scales well with number of features.
- **Variants** - `Batch` \& `Stochastic` have different behaviour while converging.
    - `Batch` converges slowly and could be trapped in a local minima (in case of non-convex optimization problems) depending on the learning rate.
    - `Stochastic` doesn't converge easily and keeps jumping around

In [1]:
import numpy as np
from sklearn.linear_model import SGDRegressor

In [9]:
# Batch Gradient Descent

ETA = 0.07
N_ITER = 1000
m = 100

# Stochastic Gradient Descent

N_EPOCHS=100

In [3]:
X = 2 * np.random.rand(m,1)
y = 3 + 4*X + np.random.rand(m,1)

In [4]:
X_b = np.c_[np.ones((m,1)), X]
X_b.shape

(100, 2)

In [5]:
theta_random = np.random.randn(2,1) # random_initialization
theta_random

array([[-1.3790391 ],
       [ 0.53659451]])

### Batch Gradient Descent

In [6]:
for _ in range(N_ITER):
    gradients = 2/m * X_b.T.dot(X_b.dot(theta_random) - y)
    theta_random -= ETA * gradients
    
theta_random

array([[3.54883567],
       [3.939423  ]])

### Stochastic Gradient Descent

In [7]:
def learning_schedule(t, t0=5, t1=50):
    return t0/(t+t1)

In [10]:
theta_init = np.random.randn(2,1) # random initialization
theta_init

array([[-0.05019794],
       [-0.7452785 ]])

In [11]:
for epoch in range(N_EPOCHS):
    for i in range(m):
        
        random_idx = np.random.randint(m)
        
        X_i = X_b[random_idx:random_idx+1]
        y_i = y[random_idx:random_idx+1]
        
        gradients = 2 * X_i.T.dot(X_i.dot(theta_init) - y_i)
        
        eta = learning_schedule(epoch*m + i)
        
        theta_init -= eta*gradients
        
        
theta_init

array([[3.55351015],
       [3.93941958]])

### Notes

- Above implementation randomly picks up observations from the dataset to calculate individual gradients. However, this could lead to repetitive choice of observations.
- Below implementation from `sklearn` - `SGDRegressor` performs Linear Regression using SGD.

In [13]:
sgd_regressor = SGDRegressor(n_iter=100, penalty=None, eta0=0.07)
sgd_regressor.fit(X, y.ravel())

print("Intercept: {}, Coefficient: {}".format(sgd_regressor.intercept_, sgd_regressor.coef_))

Intercept: [3.55020373], Coefficient: [3.94151513]


Algorithm | Large m | Large n | Hyperparams | 
--- | --- | --- | --- |
Normal Equation | Fast | Slow | None |
Batch GD | Slow | Fast | 2 |
Stochastic GD | Fast | Fast | >=2 |
Mini-batch GD | Fast | Fast | >=2 |
